{% set version = "2.0.6" %}

package:
  name: bob.learn.libsvm
  version: {{ version }}

source:
  fn: bob.learn.libsvm-{{ version }}.zip
  md5: 0ab091c9a33cbed41ae1d61a0bac1664
  url: https://pypi.io/packages/source/b/bob.learn.libsvm/bob.learn.libsvm-{{ version }}.zip

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - libsvm 3.21|3.21.*
    - boost 1.61.*
    - cmake
    - pkg-config

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - libsvm 3.21|3.21.*
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.learn.libsvm

  imports:
    - bob
    - bob.learn
    - bob.learn.libsvm

  requires:
    - nose

about:
  home: http://github.com/bioidiap/bob.learn.libsvm
  license: Modified BSD License (3-clause)
  summary: Bob's Python bindings to LIBSVM

extra:
  recipe-maintainers:
    - 183amir
